class BoxListFields:
    BOXES = 'boxes'
    FIELDS = 'fields'
    SCORES = 'scores'
    LABELS = 'labels'
    MASKS = 'masks'
    DISPLAY_NAMES = 'display_names'
    KEYPOINTS = 'keypoints'
    KEYPOINT_VISIBILITIES = 'keypoint_visibilities'
    IS_CROWD = 'is_crowd'
    INSTANCE_IDS = 'instance_ids'
    TRACK_IDS = 'track_ids'
    DENSEPOSE = 'densepose'
    EMBEDDINGS = 'embeddings'
    VERTICALS = 'verticals'
    HORIZONTALS = 'horizontals'
    ADDITIONAL_FIELDS = 'additional_fields'

class ObjectDetectionFields:
    DETECTION_BOXES = 'detection_boxes'
    DETECTION_SCORES = 'detection_scores'
    DETECTION_CLASSES = 'detection_classes'
    DETECTION_KEYPOINTS = 'detection_keypoints'
    DETECTION_MASKS = 'detection_masks'
    DETECTION_TRACK_IDS = 'detection_track_ids'
    DETECTION_INSTANCE_IDS = 'detection_instance_ids'
    DETECTION_DENSEPOSE = 'detection_densepose'
    DETECTION_EMBEDDINGS = 'detection_embeddings'
    DETECTION_VERTICALS = 'detection_verticals'
    DETECTION_HORIZONTALS = 'detection_horizontals'
    DETECTION_ADDITIONAL_FIELDS = 'detection_additional_fields'
